name: clang-doc

on:
  push:
    branches: [main]

jobs:
  docs:
    name: Generate documentation with clang-doc
    if: github.repository == 'chromium/subspace'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.DOCS_SSH_PRIVATE_KEY }}

      - name: Install LLVM+Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 all

      - name: Configure
        run: |
          # Path to LLVM+Clang nightly that we have installed.
          export LLVM_DIR="/usr/lib/llvm-16/lib/cmake/llvm"
          export Clang_DIR="/usr/lib/llvm-16/lib/cmake/clang"

          sudo apt install build-essential cmake ninja-build
          cmake -G Ninja -B out -D CMAKE_EXPORT_COMPILE_COMMANDS=1

      - name: Checkout docs
        run: |
          git checkout git@github.com:danakj/subspace-docs.git docs

      - name: Generate
        run: |
          clang-doc \
            --executor=all-TUs \
            --format=html \
            --public \
            --extra-arg=-Wno-error --extra-arg=--comments-in-macros \
            --project-name=Subspace \
            --repository=https://github.com/chromium/subspace/blob/main \
            --output=docs \
            -p out compile_commands.json

      - name: Deploy
        run: |
          cd docs
          git add docs
          git commit docs -m "Update docs"
          git push origin

