name: docs

on:
  push:
    branches: [main]

jobs:
  docs:
    name: Generate documentation
    if: github.repository == 'chromium/subspace'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure
        run: |
          sudo apt install build-essential cmake ninja-build
          cmake -G Ninja -B out -D CMAKE_EXPORT_COMPILE_COMMANDS=1
      
      - name: Documentation
        uses: hdoc/hdoc-github-action@v2
        with:
          compile-commands-path: out/compile_commands.json
          hdoc-api-key: ${{ secrets.HDOC_PROJECT_API_KEY }}
